# Book settings
title: My sample book
author: The Jupyter Book Community
logo: 'logo.png'


execute:
  execute_notebooks: cache


html:
  home_page_in_navbar: false
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  baseurl: https://op07n.github.io/jupyterbook-testvideo1/

repository:
  url: https://github.com/op07n/jupyterbook-testvideo1
  branch: master
  path_to_book: .

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://notebooks.gesis.org/binder"
  colab_url: "https://colab.research.google.com"
  thebe: true
